from collections import dequef

fila = deque([])
fila.append(5)
fila.append(3)
print(fila.popleft())
fila.append(2)
fila.append(8)
print(fila.popleft())
print(fila.popleft())
fila.append(9)
fila.append(1)
print(fila.popleft())
fila.append(7)
fila.append(6)
print(fila.popleft())
print(fila.popleft())
fila.append(4)
print(fila.popleft())
print(fila.popleft())