pilha = []
pilha.append(5)
pilha.append(3)
print(pilha.pop())
pilha.append(2)
pilha.append(8)
print(pilha.pop())
print(pilha.pop())
pilha.append(9)
pilha.append(1)
print(pilha.pop())
pilha.append(7)
pilha.append(6)
print(pilha.pop())
print(pilha.pop())
pilha.append(4)
print(pilha.pop())
print(pilha.pop())
